#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
# large spacer
# defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'
# small spacer
defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="small-spacer-tile";}'
killall Dock
