#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

lsgit() {
	{
		[[ -d "$PWD/.git" ]] && printf '%s\n' "$PWD"
		fd '^.git$' "$@" --type=d --hidden --no-ignore --max-depth=2 | {
			while read -r line; do
				[[ $line == '.git/' ]] && continue
				printf '%s\n' "./${line%%.git/}"
			done
		}
	} |
		xargs -I{} bash -c 'echo "{}:	$(cd {}; git rev-parse --abbrev-ref HEAD)"' |
		column -t
}

lsgit "$@"
