#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s expand_aliases

alias wait-for-job-slot='while [[ $(jobs -p | wc -w) -ge $(nproc) ]]; do wait -n; done;'

unwrap-to-eponymous-directory() {
  zipfile="$1"
  zipdir=$(basename "${zipfile%.*}")
  7z x "$zipfile" -o"$zipdir" -y
}

main() {
  local file
  for file in "$@"; do
    [[ $file =~ \.(zip|rar|7z)$ ]] || continue
    wait-for-job-slot
    unwrap-to-eponymous-directory "$file" &
  done
  wait
}

main "$@"
