#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

clog() {
	pushd "$HOME/notes/stripe/captains-log" >/dev/null 2>&1
	TODAYS_DATE="$(date -Idate)"
	TODAYS_LOG="$TODAYS_DATE.md"
	LAST_FILE="$(ls -A | tail -n 1)"

	if [[ $TODAYS_LOG != "$LAST_FILE" ]]; then
		{
			echo "# Captains Log - $TODAYS_DATE"
			echo
			echo "## Notes"
			echo
		} >>"$TODAYS_LOG"
		sed -z "s/^.*## Tasks/## Tasks/g" <"$LAST_FILE" >>"$TODAYS_LOG"
	fi

	nvim "$TODAYS_LOG" -c ":ijump! /## Tasks" -c ":normal k"
}

clog
