#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

help() {
  cat <<- EOF
		Usage:
		  uniqr must receive lines to sift over stdin or files to sift via arguments:
		Example:
		  $ uniqr < filename.txt
		    or
		  $ unqr filename
	EOF

}

uniq-without-sort() {
  awk '!a[$0]++'
}

for-files() {
  local file
  for file in "$@"; do
    uniq-without-sort < "$file"
  done
}

stdin-is-pipe && uniq-without-sort ||
  has-args && for-files "$@" ||
  help
