#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

while clipnotify; do
  entries=($(xclip -selection clipboard -o | egrep '^entity|^.*?{') )
  for entry in "${entries[@]}"; do
    echo "$entry" | sed -E 's/.*\| \{/{/g;'|jq
  done
  echo '-----------------------------------------------'
done
