#!/usr/bin/env bash
# shellcheck disable=SC2016
set -uo pipefail
IFS=$'\n'

main() {
  local cores
  cores="$(nproc)"
  IFS=$'\n' # redundant, but good practice
  echo "$*" | xargs -P"$cores" -I{} bash -c 'mime="$(file -i "{}" | cut -d":" -f2 )"; [[ $mime != *"video"* ]] && echo "{}"'
}

main "$@"
