#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

pbpaste |
  pandoc -f markdown -t HTML |
  sed 's/<br> /<br>/g' | # pandoc adds a space after <br>, which I don't want
  tee /dev/stderr |
  hexdump -ve '1/1 "%.2x"' |
  xargs printf 'set the clipboard to {text:" ", «class HTML»:«data HTML%s»}' |
  osascript -
