#!/usr/bin/env bash
set -euo pipefail
shopt -s expand_aliases
IFS=$'\n\t'

# osascript -e 'the clipboard as «class RTF»'

[[ $OSTYPE == "darwin"* ]] && alias is-darwin="true" && alias is-linux="false"
[[ $OSTYPE == "linux"*  ]] && alias is-darwin="false" && alias is-linux="true"

is-darwin &&
  {
    osascript -e 'the clipboard as «class HTML»' 2>/dev/null |
      perl -ne 'print chr foreach unpack("C*",pack("H*",substr($_,11,-3)))' |
      pandoc --wrap=none -f HTML -t gfm-raw_html | pbcopy
    pbpaste
  }
is-linux && {
  xclip -o -t text/html |
    pandoc --wrap=none -f HTML -t gfm-raw_html |
    xclip
}
