#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

usage() {
  echo "Usage: \$ $(basename "$0") -s<delimiter> <col1>,...,<coln> < file-to-read" 1>&2
  echo "  \$ $(basename "$0") -s<delimiter> <col1>,...,<coln> < file-to-read" 1>&2
  echo "Example:"
  # shellcheck disable=SC2028 # we want to show '\n'
  echo "\$ printf '1,2,3,4\n5,6,7,8\n9,10,11,12\n' | take -s , 2,4"
  echo "2 4"
  echo "6 8"
  echo "10 12"
  exit 1
}

take() {
  local to_print="{ print $1 }"
  local separator="$2"
  # echo "${to_print=}"
  # echo "${separator=}"
  if [[ -z $separator ]]; then
    cat - | awk "$to_print"
  else
    cat - | awk -F"$separator" "$to_print"
  fi
  # cat - | awk "$sep_arg" "{ print $columns }"
}

main() {
  local opt=""
  local separator=""
  while getopts ":s:" opt; do
    case "$opt" in
      s)
        separator=${OPTARG}
        ;;
      *)
        usage
        ;;
    esac
  done
  shift $((OPTIND - 1))

  IFS=" "
  take "$(echo "$*" | sed -zE 's/\n//g; s/ /,/g; s/,+/,/g; s/[0-9]+/$&/g')" "$separator"
}
main "$@"
