#!/usr/bin/env bash
set -x
set -euo pipefail
IFS=$'\n\t'
# Dependencies: tesseract-ocr imagemagick scrot xsel

OS_IMPL="$(uname -s)"
TMP_IMG="$(mktemp)"
# echo "$TMP_IMG"
trap 'rm "$TMP_IMG"*' EXIT
mkdir -p "$HOME/Pictures/SCREENSHOTS"

if [[ $OS_IMPL == 'Darwin' ]]; then
  SCR_IMG="$HOME/Pictures/SCREENSHOTS/SCREENSHOT__$(date -Iseconds | sed -E 's/:/./g; s/T/__/g; s/-[0-9]{2}\.[0-9]{2}$//g')"
  screencapture -s "$SCR_IMG.png"
else
  SCR_IMG="$HOME/Pictures/SCREENSHOTS/SCREENSHOT_$(date --iso-8601=seconds)"
  scrot -s "$SCR_IMG.png" -q 100
fi

cp "$SCR_IMG.png" "$TMP_IMG.png"
#should increase detection rate
mogrify -colorspace gray -modulate 100,0 -resize 400% "$TMP_IMG.png"

tesseract "$TMP_IMG.png" "$TMP_IMG" &>/dev/null
if [[ $OS_IMPL == 'Darwin' ]]; then
  cat "$TMP_IMG.txt" | pbcopy
else
  cat "$TMP_IMG.txt" | xclip -selection clipboard
fi
