#!/usr/bin/env bash
# shellcheck disable=SC2086,SC2048,SC2155
set -euo pipefail
IFS=$'\n\t'
IFS=$' '

clean() {
  # Usage: trim_all "   example   string    "
  #
  set -f
  set -- $*
  printf '%s\n' "$*"
  set +f
}

main() {
  # example entry:
  # * [2023-04-26 12:06:53 CDT] made script to make itemized list of accomplishments
  local brag="$(clean "$@")"
  if [[ -n $brag ]]; then
    echo "- [$(date '+%Y-%m-%d %H:%M:%S %Z')] $brag" >> "$HOME/notes/stripe/brag-log.md"
  fi
}

main  "$@"
