#!/bin/bash
#
#   This file echoes a bunch of color codes to the
#   terminal to demonstrate what's available.  Each
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a
#   test use of that color on all nine background
#   colors (default + 8 escapes).
#
#   Copied from http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html

EXTENDED=${1:-}

colorchart() {
	local fg bg
	foregrounds=(
		'm' '1m'
		'30m' '1;30m' '31m' '1;31m'
		'32m' '1;32m' '33m' '1;33m'
		'34m' '1;34m' '35m' '1;35m'
		'36m' '1;36m' '37m' '1;37m'
	)
	backgrounds=('40m' '41m' '42m' '43m' '44m' '45m' '46m' '47m')
	if [[ $EXTENDED == "extended" ]]; then
		foregrounds=("${foregrounds[@]}"
			'90m' '1;90m' '91m' '1;91m'
			'92m' '1;92m' '99m' '1;99m'
			'94m' '1;94m' '95m' '1;95m'
			'96m' '1;96m' '97m' '1;97m'
		)
		backgrounds=("${backgrounds[@]}"
			'100m' '101m' '102m' '103m' '104m' '105m' '106m' '107m'
		)
	fi

	T='gYw' # The test text
	printf '             '
	for BG in "${backgrounds[@]}"; do
		printf '%5s   ' "$BG"
	done
	printf '\n'
	for FGs in "${foregrounds[@]}"; do
		FG=${FGs// /}
		printf '%6s \033[%s%s' "$FG" "$FG" "  $T"
		for BG in "${backgrounds[@]}"; do
			# echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m"
			printf ' \033[%s\033[%s%s\033[0m' "$FG" "$BG" "  $T  "
		done
		echo
	done
}
truecolorcheck() {
	local columns
	if [[ $EXTENDED == "extended" ]]; then
		awk 'BEGIN{
  s="/\\/\\/\\/\\/\\"; s=s s s s s s s s s s s s s s;
  for (colnum = 0; colnum<144; colnum++) {
    r = 255-(colnum*255/143);
    g = (colnum*510/143);
    b = (colnum*255/143);
    if (g>255) g = 510-g;
      printf "\033[48;2;%d;%d;%dm", r,g,b;
      printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
      printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
  }'
	else
		awk 'BEGIN{
  s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
  for (colnum = 0; colnum<77; colnum++) {
    r = 255-(colnum*255/76);
    g = (colnum*510/76);
    b = (colnum*255/76);
    if (g>255) g = 510-g;
      printf "\033[48;2;%d;%d;%dm", r,g,b;
      printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
      printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
  }'
	fi
}

truecolorcheck
colorchart
printf '\n'
truecolorcheck
printf '\n'
