#!/usr/bin/env bash
CUSTOM_IFS="$IFS"
set -euo pipefail
IFS=$'\n\t'

set -euo pipefail

CSV=$1
START_COL=${2:-1}
END_COL=${3:-2}
shift 3
PLOT_TITLE=${*:-testplot}
PLOT_OUT="$(echo "$PLOT_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/ /_/g').png"

gnuplot -e "
set terminal pngcairo size 1920,1080 enhanced font 'Rounded Elegance,9';
set title '$PLOT_TITLE';
set output '$PLOT_OUT';
set style data histogram;
set datafile separator ',';
set key outside;
plot for [col=$START_COL:$END_COL] '$CSV' using 0:col with lines title columnheader
"
echo "Plot at '$PLOT_OUT'"
