#!/usr/bin/env bash

###
## Interactive search.
## Usage: `ff` or `ff <folder>`.
##
cd "${1:-.}" || exit # go to provided folder or noop
RG_DEFAULT_COMMAND="fd --ignore-case --no-ignore"

for_i
mapfile -t selected < <(
	FZF_DEFAULT_COMMAND="fd"               fzf \
		-m \
		-e \
		--ansi \
		--reverse \
		--bind "ctrl-a:select-all" \
		--bind "f12:execute-silent:(subl -b {})" \
		--bind "change:reload:$RG_DEFAULT_COMMAND {q} || true" \
		--preview "bat --color always {}"
)

[[ -n $selected   ]] && nvim "${selected[@]}" # open multiple files in editor
