#!/usr/bin/env bash

###
## Interactive search.
## Usage: `ff` or `ff <folder>`.
##
cd "${1:-.}" || exit # go to provided folder or noop
RG_DEFAULT_COMMAND="rg --ignore-case --files-with-matches --no-ignore"

mapfile -t selected < <(
	FZF_DEFAULT_COMMAND="rg --files"                       fzf \
		-m \
		-e \
		--ansi \
		--reverse \
		--bind "ctrl-a:select-all" \
		--bind "f12:execute-silent:(subl -b {})" \
		--bind "change:reload:$RG_DEFAULT_COMMAND {q} || true" \
		--preview "rg -i --pretty --context 2 {q} {}" | cut -d":" -f1,2
)

[[ -n $selected   ]] && nvim "${selected[@]}" # open multiple files in editor
