#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# errors out if not in git repo, silent if in repo.
git remote -v >/dev/null

LINKED_FILE="${1:-}"
CUR_REPO="$(git remote -v | grep fetch | awk '{print $2}' | cut -d: -f2 | cut -d. -f1)"
CUR_SHA="$(git rev-parse HEAD)"

printf "https://github.com/%s/tree/%s/%s\n" "$CUR_REPO" "$CUR_SHA" "$LINKED_FILE"
