#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cleanup() {
  :
}
trap "cleanup" EXIT

main() {
  cat "$@" | gsed -z 's/</\n</g' | sed 's/&nbsp/\&amp;nbsp/g; s|^\(<img .*\)>$|\1/>|g; s|<hr>|<hr/>|g; s|<br>|<br/>|g;' | yq -pxml -oxml | pbcopy
}

main "$@"
