#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# arbitrarily evaluate and prepend stdout of command to stdout of input
# ex: > source somescript.sh | prepend "    "
#     > ./somescript.sh | prepend "`hostname` "

while IFS= read -r line; do
  echo "${*} $line"
done
