#!/usr/bin/env bash
set -uo pipefail
IFS=$'\n\t'

shopt -s expand_aliases

alias has-args='[[ $# != 0 ]]'

get-vid-stats() {
  local vid
  vid="$1"
  ffmpeg -v error -i "$vid" -map 0:v -map 0:a -f null -max_muxing_queue_size 1024 - >"${vid}.errors" 2>&1
  if [[ -s "$vid".errors ]]; then
    echo "errors found in $vid"
  else
    rm "${vid}.errors"
  fi

}

main() {
  local file
  for file in "$@"; do
    [[ $(file -i "$file" | cut -d':' -f2 | sed 's|/.*||g;s/\s*//g') == "video" ]] || continue
    get-vid-stats "$file"
  done
}
has-args && main "$@"
